name: Deploy to ECS

on:
  push:
    branches:
      - main  # 监听 main 分支的推送
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm i
      - name: Build
        run: pnpm docs:build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/.vitepress/dist

    - name: Transfer files to ECS
      uses: appleboy/ssh-action@master
      with:
        host: 47.120.76.214
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          mkdir -p /unibest-docs
          rm -rf /unibest-docs/*
          scp -r ./* root@47.120.76.214:/unibest-docs

    - name: Reload Nginx
      uses: appleboy/ssh-action@master
      with:
        host: 47.120.76.214
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo systemctl reload nginx
